# -- * ruby * --
Vagrant.configure("2") do |config|
    config.vm.provider "docker" do |d|
        d.vagrant_vagrantfile = "proxy-vm/Vagrantfile"
        d.build_dir = "."
    end
    config.vm.network :forwarded_port, guest: 80, host: 8080
end
